version: '3.8'

services:
  overlap-api:
    build:
      context: ./api
      dockerfile: src/Employees.Api/Dockerfile
    image: overlap-api:latest
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
